# Clase del 25/08/2016

#Crear Vectores con la función vector
x <- vector(mode="numeric", length = 5L)
x

#Crear vectores con la función c
x <- c(0.5,0.6)
x
class(x)

x <- c(TRUE, FALSE, T, F)
x
class(x)

x <- 10:0
x
class(x)

x <- c(1+2i,5,3+9i,-4-5i)
x
class(x)

x <- c("a","b","c","d")
x
class(x)

# Mezcla de objetos en un vector
y <- c(1.7,"a")    #caracter
y
class(y)

y <- c(TRUE,2)     #numérico
y
class(y)

y <- c("a", TRUE)  #caracter
y
class(y)

y <- c(TRUE,10L,8.5,1+1i,"Nacho")
y
class(y)

# Orden de coacción/coerción explícita
# 1 character
# 2 complex
# 3 numeric
# 4 integer
# 5 logical

# Coerción explícita
z <- 0:6
class(z)
as.numeric(z)
as.logical(z)
as.character(z)

z <- c(1+2i,3+4i,8, 0+3i,0)
as.logical(z)

z <- c("Programación","Actuarial","III")
as.numeric(z)
as.logical(z)
as.complex(z)

# LISTAS (es como un vector... pero de vectores y c/u tiene
# su propia clase)
x <- list(1,"a",TRUE,1+4i)
x
class(x)

# MATRÍCES
m <- matrix(nrow = 2, ncol = 3)
m
dim(m)
attributes(m)
# Cambio de Dimensiones de 2x3 a 3x2
dim(m) <- c(3,2)
m
#Crear una matriz con datos
m <- matrix(1:6,3,2)
m

m <- matrix(1:6,3,3,T)
m
class(m)
str(m)

dim(m) <- c(2,5) #Esto va a producir error

x <- c(1,2,3)
y <- c("a","b","c")
z <- c(x,y)
z

m1 <- rbind(m,x)
m1

m2 <- cbind(m,x)
m2

rbind(m1,y)
cbind(m2,y)

#Factores
x <- factor(c("si","no","si","si","no","si","no"))
x
table(x)
unclass(x)
x <- factor(c("si","no","si","si","no","si","no"),levels = c("si","no"))

x <- factor(c("azul","azul","rojo","azul","amarillo","verde","azul"))
x
table(x)

#Valores Faltantes
x <- c(1,2,NA,10,3)
is.na(x)
is.nan(x)

x <- c(1,2,NaN,10,3)
is.na(x)
is.nan(x)

#Data Frames
x <- data.frame(Erick = 1:4 , Lori = c(T,T,F,F))
row.names(x) <- c("Primero","segundo","tercero","cuarto")
x
nrow(x)
ncol(x)
attributes(x)
names(x) <- c("Yarely","Karen")
x

#Los nombres no son exclusivos de los data frames
x <- 1:3
names(x) #NULL
names(x) <- c("Hugo","Paco","Luis")
x

x <- list(a=1:10,b=100:91,c=51:60)
x
names(x) <- c("Seq1","SEQ2","sEq3")
x


m <- matrix(1:4, 2,2)
m
attributes(m)
dimnames(m) <- list(c("fil1","fil2"),c("col1","col2"))
m

#Lectura de Datos
getwd()
setwd("~/GitHub/Programacion_Actuarial_III_OT2016")
data <- read.csv("Datos_S&P.csv")
data <- read.table("Datos_S&P.csv",T,",")
data

? matrix
m <- matrix(nrow = 2, ncol = 3)
m
dim(m)
attributes(m)
#cambio de dimensiones de 2x3 a 3x2
dim(m) <- c(3,2)
m
#Crear una matriz con datos
m <- matrix(1:6,3,2)
m


m <- matrix(1:6,3,2,T)
m


m <- matrix(1:6,3,3)
m
#Replica datos

class(m)
str(m)

dim(m) <- c(2,5) #esto produce error

x <- c(1,2,3)
y <- c("a","b","c")
z <- c(x,y)
z

m1 <- rbind(m,x)
m1

m2 <- cbind(m,x)
m2

m1 <-rbind(m,y)
m1

m2 <- cbind(m,y)
m2

install.packages("rmarkdown")




#Factores
x <- factor(c("si","no","si","si","no","si","no"))
x
table(x)
unclass(x)
x <- factor(c("si","no","si","si","no","si","no"), levels = c("si", "no"))
x
unclass(x)

x <- factor(c("azul","azul","rojo","azul","amarillo","verde","azul"))
x
table(x)
unclass(x)

#Valores faltantes
x <- c(1,2,NaN,10,3)
is.na(x)
is.nan(x)


#Data Frames
x <- data.frame(Erick = 1:4, Lori = c(T,T,F,F))
row.names(x) <- c("Primero","segundo", "tercero","cuarto")
x
nrow(x)
ncol(x)
attributes(x)

names(x) <- c("Yarely","Karen")
x
#Los nombres no son exclusivos de los data frames
x <- 1:3
names (x) #NULL
names (x) <- c("Hugo","Paco","Luis")
x
x <- list(a=1:10,b=100:91,c=51:60)
x
names(x) <- c("Seq1","SEQ2","sEq3")
x



m <- matrix(1:4,2,2)
m
attributes(m)
dimnames(m) <- list(c("fil1","fil2"),c("col1","col2"))
m

m <- matrix(NA,5,6)
m
dimnames(m) <- list(c(1:5),c("A","B","C","D","E","F"))
m
#Lectura de datos
getwd()
setwd("~/GitHub/Programacion_Actuarial_III_OT2016")
data <- read.csv("Datos_S&P.csv")
data <- read.table("Datos_S&P.csv",T, ",",nrows = 100)
args(read.table)
clases <- sapply(data,class)
data <- read.table("Datos_S&P.csv",T, ",",colClasses = clases)

data

#Uso de dget y dput
y <- data.frame(a=1, b="a")
dput(y)
dput(y, file="y.R")
nueva.y <-dget("y.R")
y
nueva.y

x <- "Programación Actuarial III"
y <- data.frame(a=1,b="a")
dump(c("x","y"), file= "data.R")
rm(x,y)
source("data.R")
x
head(airquality)
dput(airquality,file = "airquiality.R")

con <- url("http://www.fcfm.buap.mx/","r")
x <- readLines(con,7)
x

#Creamos un vector
x <- c("a","b","c","c","d","e")
#Veamos el vector
x
#Extraemos elementos con []
x[1]
x[2]
#También podemos extraer una secuencia de elementos
x[1:4]
#Es posible extraer los elementos que cuplen una restricción
x[x<"b"]
#De manera equivalente se puede obtener un vector lógico
u <- x== "c"
u
x[u]

#Creamos una lista
x <- list(foo = 1:4, bar=0.6)
#Extraemos el primer elemento de la lista
#ese elemento es una lista que contiene una secuencia
x[1]

#Extraemos nuevamente el primer elemento de la lista
#ahora el elemento es la secuencia en si
x[[1]]
#Extraemos un elemento por nombre
x$bar
x[["bar"]]
x["bar"]


x$foo [2]

#Creamos una lista de 3 elementos
x <- list(foo= 1:4, bar=0.6, baz ="Hola")
# Extraemos el primer y tercer elemento de la lista
x[c(1,3)]
#toma el primer y tercer elemento de la lista
x[[c(1,3)]]
#toma ell tercer elemento del primer objeto(argumento)

x <- list(foo= 1:4, bar=0.6, baz ="Hola")
name <- "foo"
x$name
x$foo

#Se pueden extraer elementos de los elementos extraidos
x <- list(a = list(10,12,14), b = list(3.14,2.81))
x[[c(1,3)]]
x[[1]][[3]]
x[[c(2,1)]]

#subconjunto de una matriz
x <- matrix(1:6, 2,3)
x
#extraer un dato
x[1,2]
x[2,1]
x[1,]   #extraer fila
x[,2]  #extraer columna

x <- matrix(1:6, 2,3)
x
#El resultado de un vector
x[1,2]

#Con drop=false, se mantiene la dimension y el resultado
# será una matriz

x[1,2,drop= FALSE]


x <- matrix(1:6, 2,3)
#si dejamos solamente el espacio, el resultado será un vector 
x[1,]
#si usamos drop=false, el resultado será una matriz
x[1,,drop=FALSE]


#R puede encontrar el nombre de algunos objetos de manera parcial
x <- list(aardvark = 1:5)
x$a
x[["a"]]
x[["a",exact=FALSE]]

#valores faltantes
airquality[1:6,] #extrae las primeras 6 filas y columnas
completos <- complete.cases(airquality) 
completos #filas con datos faltantes

airquality[completos,] #extrae filas completas
airquality[completos,][1:6,]#extrae las primeras 6 filas completas

airquality[1:6,][completos,]
x <- c(cor(airquality[completos,3],airquality[completos,4]))
x

#Operaciones vectorizadas
x <- 1:4; y <- 6:9 #escribir dos operaciones separándolas con ;
x + y
x>2
x>=2
y==8
x * y
x/y


x <- matrix(1:4,2,2); y <- matrix(rep(10,4),2,2)
x*y
x/y
x%*%y #multiplicación de matrices

#Estructuras de control

for(i in 1:10){print(i)}

x <- c("a","b","c","d")
for(i in 1:4){print (x[i])}
for(i in seq_along(x)){print(x[i])}
for (letras in x){print (letras)}
for(i in 1:4) print(x[i])

x <- matrix(1:6,2,3)
for(i in z){print (z[i])}
z
for(i in seq_len(nrow(x))){ for(j in seq_len(ncol(x))){print(x[i,j])}}

#ciclo while
count <- 0 
while(count)
  
  z <- 5
x <-c()
for(i in 1:100)
  
 
  z <- 5

 
x
caminata <- x
plot(caminata)

str(caminata)
?plot
plot(caminata, type="l")
#caminata aleatoria  ==igual lógico(V o F)
# && se evalua un sólo número, V o F
#distribución binomial
x <-c()
z <- 5
while (z>=3 && z<=10) { 
  print(z)
  moneda <- rbinom(1,1,0.5) 
  x<- c(x,y)
  if (moneda==1){  
    z<- z+0.5
  } else {  
    z <- z-0.5
  } 
}
x



x0 <- 1
tol <- 1e-8
repeat{
  x1 <- calculaestimado(x0)
  if(abs(x1-x0) < tol){
    break
  }else{
      x0 <- x1
    }
}

#se utiliza next para no hacer una iteración en un ciclo
for(i in 1:100){
  if(i <- 20){
    next
    #evita hacer las primeras 20 iteraciones
  }
  #Otras instrucciones
}


#creación de funciones
suma2 <- function(z,w){
  z+w
}
suma2(2,3)
suma2(1,3)  
  mayor10 <- function(z){
  z[z>10]  
}

  mayorque <- function(z,n){
    z[z>n]  
  }
promediocol <- function(z, quitar.NA = TRUE){
  nc= ncol(z)
  medias <- vector("numeric", nc)
  for (i in 1:nc) {
    medias[i] <- mean(z[,i], na.rm = quitar.NA)
  }
  medias
}
 promediocol(as.data.frame(c(1,2,3,NA)))
 
 
 #Evaluación Perezosa
  f <- function(a,b){
    a^2
  }
  f(2)
  f(3,NA)
  
  f <- function(a,b){
    print(a)
    print(b)
  }
  f(2)
  myplot <- function(x,y,type="l",...){
    plot(x,y,type=type,...)
  }
  ?plot
  
  args(paste)

  getwd()
  setwd(paste(getwd(),"/GitHub/Programacion_Actuarial_III_OT16/"))
        
  
  
  
  completos("specdata",1)
  completos("specdata",c(2,4,8,10,12))
  
  completos("specdata",30:25)
  
  
  lm
  lm <- function(x){x*x}
  lm
  rm(lm)
  lm
  
  search()
  library(ggplot2)
  
  hacer.potencia <- function(n){
    potencia <- function(x){
      x^n
    }
    potencia
  }
  cubica <- hacer.potencia(3)
    cuadrada <- hacer.potencia(2)
  
    cubica(3)
    cuadrada(3)
    
    
    
    ls(environment(cubica))
    get("n", environment(cubica))
    ls(environment(cuadrada))
    get("n",environment(cuadrada))
    
    
y <- 10 
f <- function(x){
  y <- 2
  y^2+g(x)
}
g <- function(x){
  x*y
}

#Prueba de 4 espacios
####Tabulación
    Tabulación

    
x <- as.Date("1970-01-01")  #Año, mes, día
x
unclass(x)
unclass(as.Date("2016-09-26"))

date()
as.Pos

lapply
x <- list(a=1:5,b=rnorm(10000))
lapply(x,mean)

x <- list(a=1:5,b=rnorm(10), c=rnorm(10,1), d= rnorm(10,2))
lapply(x,mean)

x <- 1:4
lapply(x, runif)

?runif

x <- 1:4
lapply(x, runif, max=15, min=5)

x <- list(a=1:5,b=rnorm(10), c=rnorm(10,1), d= rnorm(10,2))
sapply(x,mean) #convierte lista en vector


x <- 1:4
sapply(x,ruinf) #error

x <- 1:4
sapply(x, runif, max=15, min=5)

x <- matrix(rnorm(200),20,10)
apply(x, 2, mean)
apply(x, 1, sum)

rowsums=apply(x, 1, sum)
rowMeans= apply(x, 1, mean)
colSums=apply(x, 2, sum)
colMeans=apply(x, 2, mean)

x <- matrix(rnorm(200),20,10)
apply(x, 1, quantile, probs=c(0.25,0.75))

a <- array(rnorm(2*2*10), c(2,2,10))
apply(a, c(1,2), mean)
a
rowMeans(a, dims=2)

list(rep(1,4), rep(2,3), rep(3,2), rep(4,1))
mapply(rep, 1:4,4:1)

noise <- function(n, mean, sd){
    rnorm(n, mean,sd)
}
noise(5,1,2)
noise(1:5,1:5,2)

mapply(noise, 1:5,1:5,2)
#aplicar de manera vectorizada argumentos de una funcion

x <- c(rnorm(10), runif(10),rnorm(10,1))
f <- gl(3,10)
f
tapply(x, f, mean)
tapply(x, f, mean,simplify= F)


str(split)
?split
x <- c(rnorm(10), runif(10),rnorm(10,1))
f <- gl(3,10)
f
split(x,f)
lapply(split(x,f), mean)
library(datasets)
head(airquality)

split(airquality, airquality$Month)

s <- split(airquality, airquality$Month)
lapply(s, function(x) colMeans(x[, c("Ozone", "Solar.R", "Wind")], na.rm= T)) #funcion anónima
#todos los elemntos del resultado son tamaño 3, podemos aplicar sapply
sapply(s, function(x) colMeans(x[,1:4], na.rm = T))

x <- rnorm(10)
f1 <- gl(2,5)

log(-1) #warning NaNs produced, no detiene el codigo

printmessage <- function(x) {
       if(x > 0)
               print("x is greater than zero")
       else
              print("x is less than or equal to zero")
       invisible(x)
     }

printmessage(1)
printmessage(NA)

?file.path

mean(x) #Marca error, detiene el proceso
traceback()     #encuentra dónde se produjo el error
lm(y~x)
traceback()
debug(lm)   
lm(y~x)
options(error=recover)
?Error
?options
read.csv("jcjmevkf")


str(str)
str(lm)
str(ls)#nombre y argumentos que utiliza
x <- rnorm(100)
str(x)
summary(x)

f <- gl(40,10)
f
str(f)
summary(f)

str(airquality)
m <- matrix(rnorm(100),10,10)
m
str(m)
s <- split(airquality, airquality$Month)
str(s)

x <- rnorm(10)
x

y <- rnorm(10,50,5)
y

summary(x)
summary(y)

set.seed(1)
rnorm(5)
set.seed(2)
rnorm(5)

normal1 <- rnorm(10000)
normal2 <- rnorm(10000,10,5)
hist(normal1)
summary(normal1)

hist(normal2)
summary(normal2)

rpois(10,1)
poisson1 <- rpois(10000,1)
poisson2 <- rpois(10000,10)
hist(poisson1)
hist(poisson2)

ppois(6,2)
hist(rpois(10000,2))
ppois(0,2)
lambda=2
probs <- vector(mode="numeric")
probs[1] <- ppois(0,lambda)
for( i in 1:10){
    probs[i+1] <- (ppois(i,lambda)- ppois(i-1, lambda))
}
probs[12] <- 1- ppois(10, lambda)
probs

for(i in 0:12){print(dpois(i,2))}
hist(runif(200000000,10,20))

set.seed(20)
x <- rnorm(100,0,1)
e <- rnorm(100, 0, 2)
y <- 0.5 + 2 * x + e
plot(x, y)
summary(y)

z <- 0.5+2*x
plot(x,z)
plot(z,y)

set.seed(10)
x <- rbinom(100,1,0.5)
e <- rnorm(100,0,1)
y <- 0.5 + 6 * x + e
summary(y)
plot(x, y, main = "Modelo Lineal", col="red")
?plot

#Suppose we want to simulate from a Poisson model
set.seed(1)
x <- rnorm(100)
log.mu <- 0.5 + 0.3 * x
y <- rpois(100, exp(log.mu))
summary(y)
plot(x,y, main="Modelo Poisson", col="forestgreen")

#PUASóN


set.seed(1)
sample(1:10,4)
sample(1:10,4)
sample(letters,5)
sample(1:10)
sample(1:10,replace=TRUE)

system.time(readLines("http://www.fcfm.buap.mx"))
hilbert <- function(n){
    i <- 1:n
    1/outer(i-1,i,"+")
}
hilbert(1000)
x <- hilbert(1000)
?svd
svd(x)
system.time(svd(x))
system.time(x <- hilbert(1000))
